-- ============================================================================
-- FEATURE: admin-approved password reset requests
-- ============================================================================
-- admin_users has no email or phone column, and login accounts are registered
-- against synthetic addresses (username@fmb.internal, see
-- app/api/admin/create-admin-user/route.ts) on a domain that receives no mail.
-- Supabase's resetPasswordForEmail would therefore report success and deliver
-- nowhere. So reset is brokered by a human instead: the user files a request
-- from /forgot-password, a Super Admin sees it under /users -> Reset Requests,
-- sets a new password with the existing /api/admin/change-password route, and
-- passes it to the user out of band.
--
-- Safe to run more than once.
-- ============================================================================

create table if not exists public.password_reset_requests (
  id             bigint generated by default as identity primary key,
  username       text        not null,
  admin_user_id  bigint      references public.admin_users(id) on delete set null,
  full_name      text,
  status         text        not null default 'pending',
  requested_at   timestamptz not null default now(),
  requested_ip   text,
  handled_by     bigint      references public.admin_users(id) on delete set null,
  handled_at     timestamptz,
  constraint password_reset_requests_status_check
    check (status in ('pending', 'completed', 'dismissed'))
);

-- The admin tab lists pending-first, newest-first.
create index if not exists password_reset_requests_status_idx
  on public.password_reset_requests (status, requested_at desc);

-- Backs the "one open request per account" rule enforced by the API: a user
-- mashing submit must not stack duplicate rows for an admin to wade through.
create unique index if not exists password_reset_requests_one_pending_idx
  on public.password_reset_requests (admin_user_id)
  where status = 'pending';

-- --- RLS --------------------------------------------------------------------
-- anon must NOT reach this table: it is a list of valid admin usernames.
-- The public /forgot-password page never touches PostgREST — it posts to
-- /api/auth/forgot-password, which uses the service-role key (service_role
-- bypasses RLS entirely). Only the logged-in admin UI reads these rows.
alter table public.password_reset_requests enable row level security;

revoke all on public.password_reset_requests from anon;
grant select, insert, update, delete on public.password_reset_requests to authenticated;
grant usage, select on sequence public.password_reset_requests_id_seq to authenticated;

drop policy if exists reset_requests_read_authenticated on public.password_reset_requests;
create policy reset_requests_read_authenticated
  on public.password_reset_requests for select
  to authenticated
  using (true);

drop policy if exists reset_requests_write_authenticated on public.password_reset_requests;
create policy reset_requests_write_authenticated
  on public.password_reset_requests for all
  to authenticated
  using (true)
  with check (true);

-- ============================================================================
-- VERIFY (run after applying)
--   set role anon;
--   select count(*) from public.password_reset_requests;  -- expect: permission denied
--   reset role;
--
--   select policyname, roles, cmd from pg_policies
--   where schemaname='public' and tablename='password_reset_requests';
--   -- expect exactly two rows, both {authenticated}
-- ============================================================================
